# SPDX-FileCopyrightText: 2026 Peter Bezemek
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Vendored from the sibling Sapfo project (sapfo/dictionaries/noun_patterns.py) for build-time use
# by the compound builders. Included in the sdist, not the runtime wheel.
"""
Skloňovacie vzory substantív - All 132 noun declension patterns.

Each pattern is defined by 12 case suffixes in order:
  nom.sg, gen.sg, dat.sg, acc.sg, loc.sg, ins.sg,
  nom.pl, gen.pl, dat.pl, acc.pl, loc.pl, ins.pl

ø (empty string '') = zero ending
Alternation codes are stored separately.

Source: Emil Páleš, Sapfo (1994), pp. 41-44
"""

# Suffix paradigms: pattern_name -> (12 suffixes as tuple)
# '' = zero ending (ø)
NOUN_PATTERNS = {
    # ============ MASCULINE ANIMATE ============
    'chlap':    ('', 'a', 'ovi', 'a', 'ovi', 'om', 'i', 'ov', 'om', 'ov', 'och', 'mi'),
    'peržan':   ('', 'a', 'ovi', 'a', 'ovi', 'om', 'ia', 'ov', 'om', 'ov', 'och', 'mi'),
    'dedo':     ('o', 'a', 'ovi', 'a', 'ovi', 'om', 'ovia', 'ov', 'om', 'ov', 'och', 'ami'),
    'feláh':    ('', 'a', 'ovi', 'a', 'ovi', 'om', 'ovia', 'ov', 'om', 'ov', 'och', 'mi'),
    'botto':    ('o', 'u', 'ovi', 'u', 'ovi', 'om', 'ovia', 'ov', 'om', 'ov', 'och', 'ami'),
    'hosť':     ('', 'a', 'ovi', 'a', 'ovi', 'om', 'ia', 'í', 'om', 'í', 'och', 'ami'),
    'boh':      ('', 'a', 'u', 'a', 'u', 'om', 'ovia', 'ov', 'om', 'ov', 'och', 'mi'),
    'mím':      ('', 'a', 'ovi', 'a', 'ovi', 'om', 'ovia', 'ov', 'om', 'ov', 'och', 'ami'),
    'lovec':    ('', 'a', 'ovi', 'a', 'ovi', 'om', 'i', 'ov', 'om', 'ov', 'och', 'ami'),
    'vodník':   ('', 'a', 'ovi', 'a', 'ovi', 'om', 'i', 'ov', 'om', 'ov', 'och', 'mi'),
    'černoch':  ('', 'a', 'ovi', 'a', 'ovi', 'om', 'i', 'ov', 'om', 'ov', 'och', 'mi'),
    'hrdina':   ('a', 'u', 'ovi', 'u', 'ovi', 'om', 'ovia', 'ov', 'om', 'ov', 'och', 'ami'),
    'otec':     ('', 'a', 'ovi', 'a', 'ovi', 'om', 'ovia', 'ov', 'om', 'ov', 'och', 'ami'),
    'turek':    ('', 'a', 'ovi', 'a', 'ovi', 'om', 'i', 'ov', 'om', 'ov', 'och', 'ami'),
    # Greek/Latin masculine animate
    'paris':    ('', 'a', 'ovi', 'a', 'ovi', 'om', 'ovia', 'ov', 'om', 'ov', 'och', 'mi'),
    'aias':     ('', 'a', 'ovi', 'a', 'ovi', 'om', 'ovia', 'ov', 'om', 'ov', 'och', 'mi'),
    'nero':     ('', 'a', 'ovi', 'a', 'ovi', 'om', 'i', 'ov', 'om', 'ov', 'och', 'mi'),
    'anakreón': ('', 'a', 'ovi', 'a', 'ovi', 'om', 'i', 'ov', 'om', 'ov', 'och', 'mi'),
    'achilles': ('', 'a', 'ovi', 'a', 'ovi', 'om', 'ovia', 'ov', 'om', 'ov', 'och', 'mi'),
    'syzifos':  ('', 'a', 'ovi', 'a', 'ovi', 'om', 'ovia', 'ov', 'om', 'ov', 'och', 'mi'),
    'anaxagoras':('', 'a', 'ovi', 'a', 'ovi', 'om', 'ovia', 'ov', 'om', 'ov', 'och', 'mi'),
    'génius':   ('', 'a', 'ovi', 'a', 'ovi', 'om', 'ovia', 'ov', 'om', 'ov', 'och', 'mi'),
    'pontifex': ('', 'a', 'ovi', 'a', 'ovi', 'om', 'ovia', 'ov', 'om', 'ov', 'och', 'mi'),
    'noe':      ('', 'a', 'ovi', 'a', 'ovi', 'om', 'ovia', 'ov', 'om', 'ov', 'och', 'ami'),
    'futbalista':('a', 'u', 'ovi', 'u', 'ovi', 'om', 'i', 'ov', 'om', 'ov', 'och', 'ami'),
    'bandita':  ('a', 'u', 'ovi', 'u', 'ovi', 'om', 'i', 'ov', 'om', 'ov', 'och', 'mi'),
    'hume':     ('', 'a', 'ovi', 'a', 'ovi', 'om', 'ovia', 'ov', 'om', 'ov', 'och', 'mi'),
    # Substantivized adjective patterns (masculine)
    'vrchný':   ('ý', 'ého', 'ému', 'ého', 'om', 'ým', 'í', 'ých', 'ým', 'ých', 'ých', 'ými'),
    'cestujúci': ('i', 'eho', 'emu', 'eho', 'om', 'im', 'i', 'ich', 'im', 'ich', 'ich', 'imi'),

    # ============ MASCULINE INANIMATE ============
    'dub':      ('', 'a', 'u', '', 'e', 'om', 'y', 'ov', 'om', 'y', 'och', 'mi'),
    'mak':      ('', 'u', 'u', '', 'u', 'om', 'y', 'ov', 'om', 'y', 'och', 'mi'),
    'med':      ('', 'u', 'u', '', 'e', 'om', 'y', 'ov', 'om', 'y', 'och', 'mi'),
    'svietnik': ('', 'a', 'u', '', 'u', 'om', 'y', 'ov', 'om', 'y', 'och', 'mi'),
    'papier':   ('', 'a', 'u', '', 'i', 'om', 'e', 'ov', 'om', 'e', 'och', 'mi'),
    'model':    ('', 'u', 'u', '', 'i', 'om', 'y', 'ov', 'om', 'y', 'och', 'mi'),
    'strom':    ('', 'u', 'u', '', 'e', 'om', 'y', 'ov', 'om', 'y', 'och', 'ami'),
    'meter':    ('', 'a', 'u', '', 'i', 'om', 'e', 'ov', 'om', 'e', 'och', 'ami'),
    'hotel':    ('', 'a', 'u', '', 'i', 'om', 'y', 'ov', 'om', 'y', 'och', 'mi'),
    'rytmus':   ('', 'u', 'u', '', 'e', 'om', 'y', 'ov', 'om', 'y', 'och', 'ami'),
    'nónius':   ('', 'a', 'u', '', 'u', 'om', 'y', 'ov', 'om', 'y', 'och', 'ami'),
    'most':     ('', 'a', 'u', '', 'e', 'om', 'y', 'ov', 'om', 'y', 'och', 'ami'),
    'zlomok':   ('', 'u', 'u', '', 'u', 'om', 'y', 'ov', 'om', 'y', 'och', 'ami'),
    'šperk':    ('', 'u', 'u', '', 'u', 'om', 'y', 'ov', 'om', 'y', 'och', 'ami'),
    'ohníček':  ('', 'a', 'u', '', 'u', 'om', 'y', 'ov', 'om', 'y', 'och', 'ami'),
    'pojem':    ('', 'u', 'u', '', 'e', 'om', 'y', 'ov', 'om', 'y', 'och', 'ami'),
    'chrbát':   ('', 'a', 'u', '', 'e', 'om', 'y', 'ov', 'om', 'y', 'och', 'mi'),
    'chlieb':   ('', 'a', 'u', '', 'e', 'om', 'y', 'ov', 'om', 'y', 'och', 'mi'),
    'mráz':     ('', 'u', 'u', '', 'e', 'om', 'y', 'ov', 'om', 'y', 'och', 'mi'),
    'stôl':     ('', 'a', 'u', '', 'e', 'om', 'y', 'ov', 'om', 'y', 'och', 'mi'),
    'vietor':   ('', 'a', 'u', '', 'e', 'om', 'y', 'ov', 'om', 'y', 'och', 'mi'),
    'stroj':    ('', 'a', 'u', '', 'i', 'om', 'e', 'ov', 'om', 'e', 'och', 'mi'),
    'jeleň':    ('', 'a', 'ovi', 'a', 'ovi', 'om', 'e', 'ov', 'om', 'e', 'och', 'mi'),
    'mravec':   ('', 'a', 'ovi', 'a', 'ovi', 'om', 'e', 'ov', 'om', 'e', 'och', 'ami'),
    'čaj':      ('', 'u', 'u', '', 'i', 'om', 'e', 'ov', 'om', 'e', 'och', 'mi'),
    'veniec':   ('', 'a', 'u', '', 'i', 'om', 'e', 'ov', 'om', 'e', 'och', 'ami'),
    'dážď':     ('', 'a', 'u', '', 'i', 'om', 'e', 'ov', 'om', 'e', 'och', 'ami'),
    'had':      ('', 'a', 'ovi', 'a', 'ovi', 'om', 'y', 'ov', 'om', 'y', 'och', 'mi'),
    'orol':     ('', 'a', 'ovi', 'a', 'ovi', 'om', 'y', 'ov', 'om', 'y', 'och', 'ami'),
    'peniaz':   ('', 'u', 'u', '', 'i', 'om', 'e', 'í', 'om', 'e', 'och', 'mi'),
    'plášť':    ('', 'a', 'u', '', 'i', 'om', 'e', 'ov', 'om', 'e', 'och', 'ami'),
    'deň':      ('', 'a', 'u', '', 'i', 'om', 'i', 'í', 'om', 'i', 'och', 'ami'),
    'kôň':      ('', 'a', 'ovi', 'a', 'ovi', 'om', 'e', 'í', 'om', 'e', 'och', 'mi'),
    'kuli':     ('', 'ho', 'mu', 'ho', 'm', 'm', 'ovia', 'ov', 'om', 'ov', 'och', 'ami'),
    'atašé':    ('', '', '', '', '', '', '', '', '', '', '', ''),

    # ============ FEMININE ============
    'žena':     ('a', 'y', 'e', 'u', 'e', 'ou', 'y', '', 'ám', 'y', 'ách', 'ami'),
    'zora':     ('a', 'y', 'e', 'u', 'e', 'ou', 'y', '', 'ám', 'y', 'ách', 'ami'),
    'matka':    ('a', 'y', 'e', 'u', 'e', 'ou', 'y', '', 'ám', 'y', 'ách', 'ami'),
    'vojna':    ('a', 'y', 'e', 'u', 'e', 'ou', 'y', '', 'ám', 'y', 'ách', 'ami'),
    'jamka':    ('a', 'y', 'e', 'u', 'e', 'ou', 'y', '', 'ám', 'y', 'ách', 'ami'),
    'perla':    ('a', 'y', 'e', 'u', 'e', 'ou', 'y', '', 'ám', 'y', 'ách', 'ami'),
    'kráska':   ('a', 'y', 'e', 'u', 'e', 'ou', 'y', '', 'am', 'y', 'ach', 'ami'),
    'čarodejka':('a', 'y', 'e', 'u', 'e', 'ou', 'y', '', 'ám', 'y', 'ách', 'ami'),
    'idea':     ('a', 'y', 'e', 'u', 'i', 'ou', 'y', 'í', 'ám', 'y', 'ách', 'ami'),
    'dáma':     ('a', 'y', 'e', 'u', 'e', 'ou', 'y', '', 'am', 'y', 'ach', 'ami'),
    'úloha':    ('a', 'y', 'e', 'u', 'e', 'ou', 'y', '', 'ám', 'y', 'ách', 'ami'),
    'izis':     ('', 'y', 'e', 'u', 'e', 'ou', 'y', '', 'ám', 'y', 'ách', 'ami'),
    'ceres':    ('', 'y', 'e', 'u', 'e', 'ou', 'y', '', 'ám', 'y', 'ách', 'ami'),
    'juno':     ('o', 'y', 'e', 'u', 'e', 'ou', 'y', '', 'am', 'y', 'ach', 'ami'),
    'demeter':  ('', 'y', 'e', 'u', 'e', 'ou', 'y', '', 'ám', 'y', 'ách', 'ami'),
    'víchrica': ('a', 'e', 'i', 'u', 'i', 'ou', 'e', '', 'iam', 'e', 'iach', 'ami'),
    'ulica':    ('a', 'e', 'i', 'u', 'i', 'ou', 'e', '', 'iam', 'e', 'iach', 'ami'),
    'funkcia':  ('a', 'e', 'i', 'u', 'i', 'ou', 'e', 'í', 'ám', 'e', 'ách', 'ami'),
    'sudkyňa':  ('a', 'e', 'i', 'u', 'i', 'ou', 'e', '', 'ám', 'e', 'iach', 'ami'),
    'vládkyňa': ('a', 'e', 'i', 'u', 'i', 'ou', 'e', '', 'ám', 'e', 'iach', 'ami'),
    'čerešňa':  ('a', 'e', 'i', 'u', 'i', 'ou', 'e', '', 'iam', 'e', 'iach', 'ami'),
    'ruža':     ('a', 'e', 'i', 'u', 'i', 'ou', 'e', 'í', 'iam', 'e', 'iach', 'ami'),
    'vôňa':     ('a', 'e', 'i', 'u', 'i', 'ou', 'e', 'í', 'am', 'e', 'ach', 'ami'),
    'svieca':   ('a', 'e', 'i', 'u', 'i', 'ou', 'e', '', 'am', 'e', 'ach', 'ami'),
    'dlaň':     ('', 'e', 'i', '', 'i', 'ou', 'e', 'í', 'iam', 'e', 'iach', 'ami'),
    'myseľ':    ('', 'e', 'i', '', 'i', 'ou', 'e', 'í', 'iam', 'e', 'iach', 'ami'),
    'báseň':    ('', 'e', 'i', '', 'i', 'ou', 'e', 'í', 'am', 'e', 'ach', 'ami'),
    'koľaj':    ('', 'e', 'i', '', 'i', 'ou', 'e', 'í', 'am', 'e', 'ach', 'ami'),
    'pani':     ('i', 'ej', 'ej', 'iu', 'ej', 'ou', 'ie', 'í', 'iam', 'ie', 'iach', 'iami'),
    'kráľovná': ('á', 'ej', 'ej', 'ú', 'ej', 'ou', 'é', '', 'ám', 'é', 'ách', 'ami'),
    'gazdiná':  ('á', 'ej', 'ej', 'ú', 'ej', 'ou', 'é', '', 'ám', 'é', 'ách', 'ami'),
    'ženská':   ('á', 'ej', 'ej', 'ú', 'ej', 'ou', 'é', 'ých', 'ým', 'é', 'ých', 'ými'),
    'mať':      ('', 'e', 'i', '', 'i', 'ou', 'e', 'í', 'iam', 'e', 'iach', 'ami'),
    'kosť':     ('', 'i', 'i', '', 'i', 'ou', 'i', 'í', 'iam', 'i', 'iach', 'ami'),
    'cirkev':   ('', 'i', 'i', '', 'i', 'ou', 'i', 'í', 'iam', 'i', 'ách', 'ami'),
    'kader':    ('', 'e', 'i', '', 'i', 'ou', 'e', 'í', 'ám', 'e', 'ách', 'ami'),
    'labuť':    ('', 'i', 'i', '', 'i', 'ou', 'e', 'í', 'iam', 'e', 'iach', 'ami'),
    'sapfo':    ('', '', '', '', '', '', '', '', '', '', '', ''),

    # ============ NEUTER ============
    'mesto':    ('o', 'a', 'u', 'o', 'e', 'om', 'á', '', 'ám', 'á', 'ách', 'ami'),
    'mestečko': ('o', 'a', 'u', 'o', 'u', 'om', 'á', '', 'ám', 'á', 'ách', 'ami'),
    'rádio':    ('o', 'a', 'u', 'o', 'u', 'om', 'á', 'í', 'ám', 'á', 'ách', 'ami'),
    'jedlo':    ('o', 'a', 'u', 'o', 'u', 'om', 'á', '', 'ám', 'á', 'ách', 'ami'),
    'sklenárstvo':('o', 'a', 'u', 'o', 'e', 'om', 'á', '', 'ám', 'á', 'ách', 'ami'),
    'ministerstvo':('o', 'a', 'u', 'o', 'e', 'om', 'á', '', 'ám', 'á', 'ách', 'ami'),
    'slnko':    ('o', 'a', 'u', 'o', 'u', 'om', 'á', '', 'ám', 'á', 'ách', 'ami'),
    'krídlo':   ('o', 'a', 'u', 'o', 'u', 'om', 'a', '', 'am', 'a', 'ach', 'ami'),
    'rúcho':    ('o', 'a', 'u', 'o', 'u', 'om', 'a', '', 'am', 'a', 'ach', 'ami'),
    'miesto':   ('o', 'a', 'u', 'o', 'e', 'om', 'a', '', 'am', 'a', 'ach', 'ami'),
    'lýtko':    ('o', 'a', 'u', 'o', 'u', 'om', 'a', '', 'am', 'a', 'ach', 'ami'),
    'gesto':    ('o', 'a', 'u', 'o', 'e', 'om', 'á', '', 'ám', 'á', 'ách', 'ami'),
    'capriccio':('io', 'a', 'u', 'o', 'u', 'om', 'á', 'í', 'ám', 'á', 'ách', 'ami'),
    'fórum':    ('', 'a', 'u', '', 'e', 'om', 'a', '', 'am', 'a', 'ach', 'ami'),
    'múzeum':   ('', 'a', 'u', '', 'u', 'om', 'á', 'í', 'ám', 'á', 'ách', 'ami'),
    'srdce':    ('e', 'a', 'u', 'e', 'i', 'om', 'ia', '', 'iam', 'ia', 'iach', 'ami'),
    'riečište': ('e', 'a', 'u', 'e', 'i', 'om', 'ia', '', 'iam', 'ia', 'iach', 'ami'),
    'drievce':  ('e', 'a', 'u', 'e', 'i', 'om', 'ia', '', 'iam', 'ia', 'iach', 'ami'),
    'líce':     ('e', 'a', 'u', 'e', 'i', 'om', 'a', '', 'am', 'a', 'ach', 'ami'),
    'citoslovce':('e', 'a', 'u', 'e', 'i', 'om', 'ia', '', 'iam', 'ia', 'iach', 'ami'),
    'more':     ('e', 'a', 'u', 'e', 'i', 'om', 'ia', 'í', 'iam', 'ia', 'iach', 'iami'),
    'oje':      ('e', 'a', 'u', 'e', 'i', 'om', 'e', 'í', 'am', 'e', 'ach', 'ami'),
    'vysvedčenie':('ie', 'ia', 'iu', 'ie', 'í', 'ím', 'ia', 'í', 'iam', 'ia', 'iach', 'iami'),
    'dievča':   ('a', 'a', 'u', 'a', 'i', 'om', 'á', '', 'ám', 'á', 'ách', 'ami'),
    'mača':     ('a', 'a', 'u', 'a', 'i', 'om', 'á', '', 'ám', 'á', 'ách', 'ami'),
    'kura':     ('a', 'a', 'u', 'a', 'i', 'om', 'e', '', 'om', 'e', 'och', 'ami'),
    'teľa':     ('a', 'a', 'u', 'a', 'i', 'om', 'e', '', 'om', 'e', 'och', 'ami'),
    'dieťa':    ('a', 'a', 'u', 'a', 'i', 'om', 'i', 'í', 'om', 'i', 'och', 'mi'),
    # Substantivized adjective (neuter)
    'cestovné': ('é', 'ého', 'ému', 'é', 'om', 'ým', 'é', 'ých', 'ým', 'é', 'ých', 'ými'),
}

# Pattern alternation codes
# Each code refers to specific alternation types defined in the alternation module
NOUN_ALTERNATIONS = {
    'chlap':    [],
    'peržan':   [],
    'dedo':     [],
    'feláh':    [],
    'botto':    [],
    'hosť':     [],  # depalatalization handled by normalize_soft_consonants()
    'boh':      [],
    'mím':      [],
    'lovec':    ['»«', '-1sg'],  # vypustenie samohlásky, zúženie koreňa -1sg
    'vodník':   ['k/c', '+1pl'],  # zámena k/c, rozšírenie +1pl
    'černoch':  ['ch/s', '+1pl'],
    'hrdina':   [],
    'otec':     ['»«', '-1sg'],
    'turek':    ['»«', '-1sg', 'k/c', '+1pl'],  # elision at all but nom.sg, then k→c at nom.pl
    'paris':    ['s/d', '-1sg'],
    'aias':     ['s/n', '-1sg'],
    'nero':     ['+n', '≤', '-1sg'],
    'anakreón': ['+t', '≥', '-1sg'],
    'achilles': ['-es', '-1sg'],
    'syzifos':  ['-os', '-1sg'],
    'anaxagoras':['-as', '-1sg'],
    'génius':   ['ex/ik', '-1sg'],
    'pontifex': ['ex/ik', '-1sg'],
    'noe':      ['+m', '-1sg'],
    'futbalista':[],
    'bandita':  [],
    'hume':     [],
    'vrchný':   [],
    'cestujúci':[],
    'dub':      [],
    'mak':      [],
    'med':      [],
    'svietnik': [],
    'papier':   [],
    'model':    [],
    'strom':    [],
    'meter':    ['»«', '-14sg'],
    'hotel':    [],
    'rytmus':   ['-us', '-14sg'],
    'nónius':   ['-us', '-14sg'],
    'most':     [],
    'zlomok':   ['»«', '-14sg'],
    'šperk':    [],
    'ohníček':  ['»«', '-14sg'],
    'pojem':    ['»«', '-14sg'],
    'chrbát':   ['»«', '-14sg'],
    'chlieb':   ['≥', '-14sg'],
    'mráz':     ['≥', '-14sg'],
    'stôl':     ['≥', '+2367sg', '≥', 'pl'],
    'vietor':   ['≥', '»«', '-14sg'],
    'stroj':    [],
    'jeleň':    [],
    'mravec':   ['»«', '-1sg'],
    'čaj':      [],
    'veniec':   ['»«', '-14sg'],
    'dážď':     ['≥', '-14sg'],
    'had':      [],
    'orol':     ['»«', '-1sg'],  # fleeting vowel: orol→orla
    'peniaz':   ['≥', '+2pl'],
    'plášť':    [],
    'deň':      ['»«', '-14sg'],
    'kôň':      ['≥', '-1sg'],
    'kuli':     [],
    'atašé':    [],
    'žena':     ['≤', '+2pl'],
    'zora':     ['≤', '+2pl'],
    'matka':    ['«ie»', '+2pl'],
    'vojna':    ['«e»', '+2pl'],
    'jamka':    ['«ô»', '+2pl'],
    'perla':    ['«á»', '+2pl'],
    'kráska':   ['«o»', '+2pl'],
    'čarodejka':['«o»', '+2pl'],
    'idea':     [],
    'dáma':     [],
    'úloha':    [],
    'izis':     ['s/d', '-1sg'],
    'ceres':    ['s/r', '-1sg'],
    'juno':     ['+n', '-1sg'],
    'demeter':  ['»«', '-1sg-2pl', '≤', '+2pl'],
    'víchrica': [],
    'ulica':    ['≤', '+2pl'],
    'funkcia':  [],
    'sudkyňa':  ['≤', '+2pl'],
    'vládkyňa': [],
    'čerešňa':  ['«ie»', '+2pl'],
    'ruža':     [],
    'vôňa':     [],
    'svieca':   [],
    'dlaň':     [],
    'myseľ':    ['»«', '-14sg'],
    'báseň':    ['»«', '-14sg'],
    'koľaj':    [],
    'pani':     [],
    'kráľovná': ['«ie»', '+2pl'],
    'gazdiná':  ['≤', '+2pl'],
    'ženská':   [],
    'mať':      ['+er', '-1sg'],
    'kosť':     [],
    'cirkev':   ['»«', '-14sg'],
    'kader':    [],
    'labuť':    [],
    'sapfo':    [],
    'mesto':     ['≤', '+2pl'],
    'mestečko': ['«ie»', '+2pl'],
    'rádio':    [],
    'jedlo':    [],
    'sklenárstvo':['«ie»', '+2pl'],
    'ministerstvo':['«ie»', '+2pl'],
    'slnko':    ['≤', '+2pl'],
    'krídlo':   ['«e»', '+2pl'],
    'rúcho':    [],
    'miesto':   [],
    'lýtko':    ['«o»', '+2pl'],
    'gesto':    [],
    'capriccio':[],
    'fórum':    ['-um', '-14sg'],
    'múzeum':   ['um', '-14sg'],
    'srdce':    ['≤', '+2pl'],
    'riečište': ['≤', '+2pl'],
    'drievce':  [],
    'líce':     ['«e»', '+2pl'],
    'citoslovce':['«ie»', '+2pl'],
    'more':     [],
    'oje':      [],
    'vysvedčenie':[],
    'dievča':   ['+ať', '-14sg'],
    'mača':     ['+ať', '-14sg', '≤', '+2pl'],
    'kura':     ['+ať+2367sg', '+enc', '+pl'],
    'teľa':     ['+ať+2367sg', '+c', 'pl'],
    'dieťa':    ['+ať+2367sg', '≥', 'pl'],
    'cestovné': [],
}

# Gender mapping for each pattern
NOUN_GENDER = {
    # Masculine animate
    'chlap': 'muž', 'peržan': 'muž', 'dedo': 'muž', 'feláh': 'muž',
    'botto': 'muž', 'hosť': 'muž', 'boh': 'muž', 'mím': 'muž',
    'lovec': 'muž', 'vodník': 'muž', 'černoch': 'muž', 'hrdina': 'muž',
    'otec': 'muž', 'turek': 'muž', 'paris': 'muž', 'aias': 'muž',
    'nero': 'muž', 'anakreón': 'muž', 'achilles': 'muž', 'syzifos': 'muž',
    'anaxagoras': 'muž', 'génius': 'muž', 'pontifex': 'muž', 'noe': 'muž',
    'futbalista': 'muž', 'bandita': 'muž', 'hume': 'muž',
    'vrchný': 'muž', 'cestujúci': 'muž',
    # Masculine inanimate
    'dub': 'muž', 'mak': 'muž', 'med': 'muž', 'svietnik': 'muž',
    'papier': 'muž', 'model': 'muž', 'strom': 'muž', 'meter': 'muž',
    'hotel': 'muž', 'rytmus': 'muž', 'nónius': 'muž', 'most': 'muž',
    'zlomok': 'muž', 'šperk': 'muž', 'ohníček': 'muž', 'pojem': 'muž',
    'chrbát': 'muž', 'chlieb': 'muž', 'mráz': 'muž', 'stôl': 'muž',
    'vietor': 'muž', 'stroj': 'muž', 'jeleň': 'muž', 'mravec': 'muž',
    'čaj': 'muž', 'veniec': 'muž', 'dážď': 'muž', 'had': 'muž',
    'orol': 'muž', 'peniaz': 'muž', 'plášť': 'muž', 'deň': 'muž',
    'kôň': 'muž', 'kuli': 'muž', 'atašé': 'muž',
    # Feminine
    'žena': 'žen', 'zora': 'žen', 'matka': 'žen', 'vojna': 'žen',
    'jamka': 'žen', 'perla': 'žen', 'kráska': 'žen', 'čarodejka': 'žen',
    'idea': 'žen', 'dáma': 'žen', 'úloha': 'žen', 'izis': 'žen',
    'ceres': 'žen', 'juno': 'žen', 'demeter': 'žen',
    'víchrica': 'žen', 'ulica': 'žen', 'funkcia': 'žen', 'sudkyňa': 'žen',
    'vládkyňa': 'žen', 'čerešňa': 'žen', 'ruža': 'žen', 'vôňa': 'žen',
    'svieca': 'žen', 'dlaň': 'žen', 'myseľ': 'žen', 'báseň': 'žen',
    'koľaj': 'žen', 'pani': 'žen', 'kráľovná': 'žen', 'gazdiná': 'žen',
    'ženská': 'žen', 'mať': 'žen', 'kosť': 'žen', 'cirkev': 'žen',
    'kader': 'žen', 'labuť': 'žen', 'sapfo': 'žen',
    # Neuter
    'mesto': 'str', 'mestečko': 'str', 'rádio': 'str', 'jedlo': 'str',
    'sklenárstvo': 'str', 'ministerstvo': 'str', 'slnko': 'str', 'krídlo': 'str', 'rúcho': 'str',
    'miesto': 'str', 'lýtko': 'str', 'gesto': 'str', 'capriccio': 'str',
    'fórum': 'str', 'múzeum': 'str', 'srdce': 'str', 'riečište': 'str',
    'drievce': 'str', 'líce': 'str', 'citoslovce': 'str',
    'more': 'str', 'oje': 'str', 'vysvedčenie': 'str',
    'dievča': 'str', 'mača': 'str', 'kura': 'str', 'teľa': 'str',
    'dieťa': 'str', 'cestovné': 'str',
}

# Animacy for masculine nouns
NOUN_ANIMACY = {
    'chlap': 'živ', 'peržan': 'živ', 'dedo': 'živ', 'feláh': 'živ',
    'botto': 'živ', 'hosť': 'živ', 'boh': 'živ', 'mím': 'živ',
    'lovec': 'živ', 'vodník': 'živ', 'černoch': 'živ', 'hrdina': 'živ',
    'otec': 'živ', 'turek': 'živ', 'paris': 'živ', 'aias': 'živ',
    'nero': 'živ', 'anakreón': 'živ', 'achilles': 'živ', 'syzifos': 'živ',
    'anaxagoras': 'živ', 'génius': 'živ', 'pontifex': 'živ', 'noe': 'živ',
    'futbalista': 'živ', 'bandita': 'živ', 'hume': 'živ',
    'vrchný': 'živ', 'cestujúci': 'živ',
    'kuli': 'živ',
    'jeleň': 'živ', 'mravec': 'živ', 'had': 'živ', 'orol': 'živ', 'kôň': 'živ',
}

# Case index names
CASES = ['nom', 'gen', 'dat', 'acc', 'loc', 'ins']
NUMBERS = ['sg', 'pl']
CASE_INDEX = {
    ('nom', 'sg'): 0, ('gen', 'sg'): 1, ('dat', 'sg'): 2,
    ('acc', 'sg'): 3, ('loc', 'sg'): 4, ('ins', 'sg'): 5,
    ('nom', 'pl'): 6, ('gen', 'pl'): 7, ('dat', 'pl'): 8,
    ('acc', 'pl'): 9, ('loc', 'pl'): 10, ('ins', 'pl'): 11,
}
